### ISSUE TITLE
no frameworks 

### ISSUE THREAD

**Issue by jackpaster** [EurekaCommunity/GenericPasswordRow#1]
The eureka framework cannot be found when I download this project. can you fix that.

**Comment by jackpaster** [comment]
@demetrio812, @marbetschar, @lognaturel, @mtnbarreto, @m-revetria I love this project very much so can you update it to swift 3.0 and resolve the framework issue please. Could you do it this week please,

**Comment by jackpaster** [comment]
can you please help me

**Comment by dernster** [comment]
@jackpaster Hi! We are reviewing this and will try to fix this as soon as we have some free time. Can't ensure 100% to do it for this week though.

**Comment by jackpaster** [comment]
could you do it by next week please

**Comment by jackpaster** [comment]
do you think its possible

**Comment by jackpaster** [comment]
@dernster could you do it by next week please. Do you think its possible

**Comment by mcousillas6** [comment]
@jackpaster Please check out feature/swift-3 branch , it has support for swift 3. You can use that one until it's reviewed and merged.

**Comment by jackpaster** [comment]
@mcousillas6  There's no pod file in this project

**Comment by jackpaster** [comment]
Where is the swift 3 branch and how can I use it. I added this to my pod file 

pod 'GenericPasswordRow', :git => 'https://github.com/EurekaCommunity/GenericPasswordRow.git', :branch => 'swift3'

but it didn't work. Can you please help me

**Comment by jackpaster** [comment]
Can you please update this project

**Comment by dernster** [comment]
@jackpaster You should use:

pod 'GenericPasswordRow', :git => 'https://github.com/EurekaCommunity/GenericPasswordRow.git', :branch => 'feature/swift-3'

**Comment by jackpaster** [comment]
@dernster The genericpasswordrow and eureka frameworks are missing in the project. There red.

**Comment by jackpaster** [comment]
@dernster can you help me.

**Comment by Ahmedshubber** [comment]
@jackpaster @dernster @mcousillas6 @demetrio812 @marbetschar +1 I had the same problem, the frameworks are missing for this project

**Comment by Ahmedshubber** [comment]
could you fix that

**Comment by ghost** [comment]
Same issue. Help needed

**Comment by ghost** [comment]
Hi there I make personal adaptation of Generic Password Cell in swift 3. I hope it can help

https://github.com/iLandes/EurekaPasswordCell

**Comment by dernster** [comment]
Hey guys, if you are trying to run the Example project you should:

1. Clone the repo
2. Switch to branch feature/swift-3
3. run the script bin/setup
4. open the workspace and run the Example target.

If you are trying to use this project from cocoapods, adding:

```
  pod 'GenericPasswordRow', :git => 'https://github.com/EurekaCommunity/GenericPasswordRow.git', :branch => 'feature/swift-3'
  pod 'Eureka'
```
to your Podfile should work. I have tested it using xcode 8.2. If you have multiple versions of Xcode installed, be sure of having Xcode 8.2 selected using the `xcode-select` command at the moment of running the `bin/setup` script.

Please let me know if this works for you guys. Thanks. @jackpaster @iLandes @Ahmedshubber

**Comment by dernster** [comment]
Guys, I'm going to close  this issue since running `bin/setup` before opening the project seems to resolve this. There is a new version [2.0.0](https://github.com/EurekaCommunity/GenericPasswordRow/releases/tag/2.0.0) with Swift 3 and Eureka 2.0.1 support. Thanks for your feedback and support!
