### ISSUE TITLE
How to fetch real password before revealing it?

### ISSUE THREAD

**Issue by everwanna** [EurekaCommunity/GenericPasswordRow#24]
What's the best practice to do it? 

I found that I have to write a subclass `MyGenericPasswordCell` of `GenericPasswordCell` and override the `togglePasswordVisibility` method. After that, I have to write a `MyGenericPasswordRow`, `_GenericPasswordRow`. The Eureka framework is not friendly to add new row type. 

Actually, I just make `visibilityButton` public, and replace the target action.

**Comment by mats-claassen** [comment]
Could you explain a bit more what you want to do?

**Comment by everwanna** [comment]
My app cannot get user's password directly. It would fetch it remotely, decrypt it then show it when user touching the revealing button. Thanks!

**Comment by mats-claassen** [comment]
Fetching the password remotely is not something this library does. You should do it independently and then set the value of the row to that password.

**Comment by everwanna** [comment]
Well, I understand that. My problem is how can I hook the toggle action so I can fetch it remotely then reveal it to user.

**Comment by mats-claassen** [comment]
Yeah in that case I think subclassing is the right way, to fetch the password and then revealing it, unless you are fine without changing `togglePasswordVisibility`.
You have a section about ]custom rows](https://github.com/xmartlabs/Eureka#custom-rows) in the Readme of Eureka and you can also follow the [blog posts](https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/) if you need help.

**Comment by everwanna** [comment]
Thanks for your respond. I forked the source code and made visibilityButton public so I can replace its target action. It works well. 😄
